name: TankLib
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    submodules: 'recursive'
            -   name: Install .NET Core 7
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 7.0.x
            -   name: Mutate Run Number
                run: |
                  $num = (997+$($Env:GITHUB_RUN_NUMBER))
                  echo "GITHUB_RUN_NUMBER_DELTA=$num" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
            -   name: Restore project
                run: dotnet restore OverwatchToolchain.sln --verbosity m -r win7-x64 -p:TargetFramework=net6.0
            -   name: Build Release
                run: dotnet publish --configuration ReleasePublish -r win7-x64 -o dist/Release -p:TargetFramework=net6.0 -f net6.0
            -   name: Upload Release
                uses: actions/upload-artifact@v2
                with:
                    name: toolchain-release
                    path: dist/Release
            -   name: Build Debug
                run: dotnet publish --configuration DebugPublish -r win7-x64 -o dist/Debug -p:TargetFramework=net6.0 -f net6.0
            -   name: Upload Debug
                uses: actions/upload-artifact@v2
                with:
                    name: toolchain-debug
                    path: dist/Debug
